---
- hosts: minus.lviv.ua
  tasks:
    - name: Update 
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    - name: install docker
      apt: pkg=docker state=installed update_cache=true
    - name: install docker-compose
      apt: pkg=docker-compose state=installed update_cache=true
